/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FilmCategory = IDL.Variant({
  'coupleTeaser' : IDL.Null,
  'reel' : IDL.Null,
  'weddingHighlights' : IDL.Null,
  'engagement' : IDL.Null,
});
export const FilmInput = IDL.Record({
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'category' : FilmCategory,
  'youtubeUrl' : IDL.Text,
});
export const FilmId = IDL.Nat;
export const Film = IDL.Record({
  'id' : FilmId,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : FilmCategory,
  'youtubeUrl' : IDL.Text,
});
export const GalleryImageInput = IDL.Record({
  'alt' : IDL.Text,
  'url' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'caption' : IDL.Text,
  'category' : IDL.Text,
});
export const GalleryImageId = IDL.Nat;
export const GalleryImage = IDL.Record({
  'id' : GalleryImageId,
  'alt' : IDL.Text,
  'url' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'createdAt' : IDL.Int,
  'caption' : IDL.Text,
  'category' : IDL.Text,
});
export const PackageInput = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'highlighted' : IDL.Bool,
  'price' : IDL.Text,
});
export const PackageId = IDL.Nat;
export const Package = IDL.Record({
  'id' : PackageId,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'highlighted' : IDL.Bool,
  'price' : IDL.Text,
});
export const TestimonialInput = IDL.Record({
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'quote' : IDL.Text,
  'photoUrl' : IDL.Text,
  'rating' : IDL.Nat,
});
export const TestimonialId = IDL.Nat;
export const Testimonial = IDL.Record({
  'id' : TestimonialId,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'quote' : IDL.Text,
  'photoUrl' : IDL.Text,
  'rating' : IDL.Nat,
});
export const InquiryId = IDL.Nat;
export const ContactInquiry = IDL.Record({
  'id' : InquiryId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'packageInterest' : IDL.Text,
  'eventDate' : IDL.Text,
});
export const InquiryInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'packageInterest' : IDL.Text,
  'eventDate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFilm' : IDL.Func([FilmInput], [Film], []),
  'createGalleryImage' : IDL.Func([GalleryImageInput], [GalleryImage], []),
  'createPackage' : IDL.Func([PackageInput], [Package], []),
  'createTestimonial' : IDL.Func([TestimonialInput], [Testimonial], []),
  'deleteFilm' : IDL.Func([FilmId], [], []),
  'deleteGalleryImage' : IDL.Func([GalleryImageId], [], []),
  'deleteInquiry' : IDL.Func([InquiryId], [], []),
  'deletePackage' : IDL.Func([PackageId], [], []),
  'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedFilms' : IDL.Func([], [IDL.Vec(Film)], ['query']),
  'getFeaturedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getFilm' : IDL.Func([FilmId], [IDL.Opt(Film)], ['query']),
  'getFilms' : IDL.Func([], [IDL.Vec(Film)], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getGalleryImagesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'getInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitInquiry' : IDL.Func([InquiryInput], [ContactInquiry], []),
  'updateFilm' : IDL.Func([FilmId, FilmInput], [IDL.Bool], []),
  'updateGalleryImage' : IDL.Func(
      [GalleryImageId, GalleryImageInput],
      [IDL.Bool],
      [],
    ),
  'updatePackage' : IDL.Func([PackageId, PackageInput], [IDL.Bool], []),
  'updateTestimonial' : IDL.Func(
      [TestimonialId, TestimonialInput],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FilmCategory = IDL.Variant({
    'coupleTeaser' : IDL.Null,
    'reel' : IDL.Null,
    'weddingHighlights' : IDL.Null,
    'engagement' : IDL.Null,
  });
  const FilmInput = IDL.Record({
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'category' : FilmCategory,
    'youtubeUrl' : IDL.Text,
  });
  const FilmId = IDL.Nat;
  const Film = IDL.Record({
    'id' : FilmId,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : FilmCategory,
    'youtubeUrl' : IDL.Text,
  });
  const GalleryImageInput = IDL.Record({
    'alt' : IDL.Text,
    'url' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'caption' : IDL.Text,
    'category' : IDL.Text,
  });
  const GalleryImageId = IDL.Nat;
  const GalleryImage = IDL.Record({
    'id' : GalleryImageId,
    'alt' : IDL.Text,
    'url' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'createdAt' : IDL.Int,
    'caption' : IDL.Text,
    'category' : IDL.Text,
  });
  const PackageInput = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'highlighted' : IDL.Bool,
    'price' : IDL.Text,
  });
  const PackageId = IDL.Nat;
  const Package = IDL.Record({
    'id' : PackageId,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'highlighted' : IDL.Bool,
    'price' : IDL.Text,
  });
  const TestimonialInput = IDL.Record({
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'quote' : IDL.Text,
    'photoUrl' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const TestimonialId = IDL.Nat;
  const Testimonial = IDL.Record({
    'id' : TestimonialId,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'quote' : IDL.Text,
    'photoUrl' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const InquiryId = IDL.Nat;
  const ContactInquiry = IDL.Record({
    'id' : InquiryId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'packageInterest' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  const InquiryInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'packageInterest' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFilm' : IDL.Func([FilmInput], [Film], []),
    'createGalleryImage' : IDL.Func([GalleryImageInput], [GalleryImage], []),
    'createPackage' : IDL.Func([PackageInput], [Package], []),
    'createTestimonial' : IDL.Func([TestimonialInput], [Testimonial], []),
    'deleteFilm' : IDL.Func([FilmId], [], []),
    'deleteGalleryImage' : IDL.Func([GalleryImageId], [], []),
    'deleteInquiry' : IDL.Func([InquiryId], [], []),
    'deletePackage' : IDL.Func([PackageId], [], []),
    'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedFilms' : IDL.Func([], [IDL.Vec(Film)], ['query']),
    'getFeaturedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getFilm' : IDL.Func([FilmId], [IDL.Opt(Film)], ['query']),
    'getFilms' : IDL.Func([], [IDL.Vec(Film)], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getGalleryImagesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'getInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitInquiry' : IDL.Func([InquiryInput], [ContactInquiry], []),
    'updateFilm' : IDL.Func([FilmId, FilmInput], [IDL.Bool], []),
    'updateGalleryImage' : IDL.Func(
        [GalleryImageId, GalleryImageInput],
        [IDL.Bool],
        [],
      ),
    'updatePackage' : IDL.Func([PackageId, PackageInput], [IDL.Bool], []),
    'updateTestimonial' : IDL.Func(
        [TestimonialId, TestimonialInput],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };