/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInquiry {
  'id' : InquiryId,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
  'packageInterest' : string,
  'eventDate' : string,
}
export interface Film {
  'id' : FilmId,
  'title' : string,
  'featured' : boolean,
  'thumbnailUrl' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : FilmCategory,
  'youtubeUrl' : string,
}
export type FilmCategory = { 'coupleTeaser' : null } |
  { 'reel' : null } |
  { 'weddingHighlights' : null } |
  { 'engagement' : null };
export type FilmId = bigint;
export interface FilmInput {
  'title' : string,
  'featured' : boolean,
  'thumbnailUrl' : string,
  'description' : string,
  'category' : FilmCategory,
  'youtubeUrl' : string,
}
export interface GalleryImage {
  'id' : GalleryImageId,
  'alt' : string,
  'url' : string,
  'displayOrder' : bigint,
  'createdAt' : bigint,
  'caption' : string,
  'category' : string,
}
export type GalleryImageId = bigint;
export interface GalleryImageInput {
  'alt' : string,
  'url' : string,
  'displayOrder' : bigint,
  'caption' : string,
  'category' : string,
}
export type InquiryId = bigint;
export interface InquiryInput {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'packageInterest' : string,
  'eventDate' : string,
}
export interface Package {
  'id' : PackageId,
  'features' : Array<string>,
  'name' : string,
  'highlighted' : boolean,
  'price' : string,
}
export type PackageId = bigint;
export interface PackageInput {
  'features' : Array<string>,
  'name' : string,
  'highlighted' : boolean,
  'price' : string,
}
export interface Testimonial {
  'id' : TestimonialId,
  'featured' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'quote' : string,
  'photoUrl' : string,
  'rating' : bigint,
}
export type TestimonialId = bigint;
export interface TestimonialInput {
  'featured' : boolean,
  'name' : string,
  'quote' : string,
  'photoUrl' : string,
  'rating' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFilm' : ActorMethod<[FilmInput], Film>,
  'createGalleryImage' : ActorMethod<[GalleryImageInput], GalleryImage>,
  'createPackage' : ActorMethod<[PackageInput], Package>,
  'createTestimonial' : ActorMethod<[TestimonialInput], Testimonial>,
  'deleteFilm' : ActorMethod<[FilmId], undefined>,
  'deleteGalleryImage' : ActorMethod<[GalleryImageId], undefined>,
  'deleteInquiry' : ActorMethod<[InquiryId], undefined>,
  'deletePackage' : ActorMethod<[PackageId], undefined>,
  'deleteTestimonial' : ActorMethod<[TestimonialId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedFilms' : ActorMethod<[], Array<Film>>,
  'getFeaturedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getFilm' : ActorMethod<[FilmId], [] | [Film]>,
  'getFilms' : ActorMethod<[], Array<Film>>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getGalleryImagesByCategory' : ActorMethod<[string], Array<GalleryImage>>,
  'getInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getPackages' : ActorMethod<[], Array<Package>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitInquiry' : ActorMethod<[InquiryInput], ContactInquiry>,
  'updateFilm' : ActorMethod<[FilmId, FilmInput], boolean>,
  'updateGalleryImage' : ActorMethod<
    [GalleryImageId, GalleryImageInput],
    boolean
  >,
  'updatePackage' : ActorMethod<[PackageId, PackageInput], boolean>,
  'updateTestimonial' : ActorMethod<[TestimonialId, TestimonialInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];