/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type FilmId = bigint;
export interface FilmInput {
    title: string;
    featured: boolean;
    thumbnailUrl: string;
    description: string;
    category: FilmCategory;
    youtubeUrl: string;
}
export interface PackageInput {
    features: Array<string>;
    name: string;
    highlighted: boolean;
    price: string;
}
export interface Film {
    id: FilmId;
    title: string;
    featured: boolean;
    thumbnailUrl: string;
    createdAt: bigint;
    description: string;
    category: FilmCategory;
    youtubeUrl: string;
}
export interface TestimonialInput {
    featured: boolean;
    name: string;
    quote: string;
    photoUrl: string;
    rating: bigint;
}
export interface Package {
    id: PackageId;
    features: Array<string>;
    name: string;
    highlighted: boolean;
    price: string;
}
export interface InquiryInput {
    name: string;
    email: string;
    message: string;
    phone: string;
    packageInterest: string;
    eventDate: string;
}
export type InquiryId = bigint;
export type GalleryImageId = bigint;
export interface GalleryImage {
    id: GalleryImageId;
    alt: string;
    url: string;
    displayOrder: bigint;
    createdAt: bigint;
    caption: string;
    category: string;
}
export type PackageId = bigint;
export interface ContactInquiry {
    id: InquiryId;
    name: string;
    createdAt: bigint;
    email: string;
    message: string;
    phone: string;
    packageInterest: string;
    eventDate: string;
}
export type TestimonialId = bigint;
export interface GalleryImageInput {
    alt: string;
    url: string;
    displayOrder: bigint;
    caption: string;
    category: string;
}
export interface Testimonial {
    id: TestimonialId;
    featured: boolean;
    name: string;
    createdAt: bigint;
    quote: string;
    photoUrl: string;
    rating: bigint;
}
export enum FilmCategory {
    coupleTeaser = "coupleTeaser",
    reel = "reel",
    weddingHighlights = "weddingHighlights",
    engagement = "engagement"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createFilm(input: FilmInput): Promise<Film>;
    createGalleryImage(input: GalleryImageInput): Promise<GalleryImage>;
    createPackage(input: PackageInput): Promise<Package>;
    createTestimonial(input: TestimonialInput): Promise<Testimonial>;
    deleteFilm(id: FilmId): Promise<void>;
    deleteGalleryImage(id: GalleryImageId): Promise<void>;
    deleteInquiry(id: InquiryId): Promise<void>;
    deletePackage(id: PackageId): Promise<void>;
    deleteTestimonial(id: TestimonialId): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getFeaturedFilms(): Promise<Array<Film>>;
    getFeaturedTestimonials(): Promise<Array<Testimonial>>;
    getFilm(id: FilmId): Promise<Film | null>;
    getFilms(): Promise<Array<Film>>;
    getGalleryImages(): Promise<Array<GalleryImage>>;
    getGalleryImagesByCategory(category: string): Promise<Array<GalleryImage>>;
    getInquiries(): Promise<Array<ContactInquiry>>;
    getPackages(): Promise<Array<Package>>;
    getTestimonials(): Promise<Array<Testimonial>>;
    isCallerAdmin(): Promise<boolean>;
    submitInquiry(input: InquiryInput): Promise<ContactInquiry>;
    updateFilm(id: FilmId, input: FilmInput): Promise<boolean>;
    updateGalleryImage(id: GalleryImageId, input: GalleryImageInput): Promise<boolean>;
    updatePackage(id: PackageId, input: PackageInput): Promise<boolean>;
    updateTestimonial(id: TestimonialId, input: TestimonialInput): Promise<boolean>;
}
import type { Film as _Film, FilmCategory as _FilmCategory, FilmId as _FilmId, FilmInput as _FilmInput, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createFilm(arg0: FilmInput): Promise<Film> {
        if (this.processError) {
            try {
                const result = await this.actor.createFilm(to_candid_FilmInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Film_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFilm(to_candid_FilmInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Film_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGalleryImage(arg0: GalleryImageInput): Promise<GalleryImage> {
        if (this.processError) {
            try {
                const result = await this.actor.createGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGalleryImage(arg0);
            return result;
        }
    }
    async createPackage(arg0: PackageInput): Promise<Package> {
        if (this.processError) {
            try {
                const result = await this.actor.createPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPackage(arg0);
            return result;
        }
    }
    async createTestimonial(arg0: TestimonialInput): Promise<Testimonial> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestimonial(arg0);
            return result;
        }
    }
    async deleteFilm(arg0: FilmId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFilm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFilm(arg0);
            return result;
        }
    }
    async deleteGalleryImage(arg0: GalleryImageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0);
            return result;
        }
    }
    async deleteInquiry(arg0: InquiryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInquiry(arg0);
            return result;
        }
    }
    async deletePackage(arg0: PackageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackage(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: TestimonialId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedFilms(): Promise<Array<Film>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedFilms();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedFilms();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedTestimonials();
            return result;
        }
    }
    async getFilm(arg0: FilmId): Promise<Film | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilm(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilm(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilms(): Promise<Array<Film>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilms();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilms();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImages();
            return result;
        }
    }
    async getGalleryImagesByCategory(arg0: string): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImagesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImagesByCategory(arg0);
            return result;
        }
    }
    async getInquiries(): Promise<Array<ContactInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiries();
            return result;
        }
    }
    async getPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackages();
            return result;
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async submitInquiry(arg0: InquiryInput): Promise<ContactInquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0);
            return result;
        }
    }
    async updateFilm(arg0: FilmId, arg1: FilmInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFilm(arg0, to_candid_FilmInput_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFilm(arg0, to_candid_FilmInput_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateGalleryImage(arg0: GalleryImageId, arg1: GalleryImageInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryImage(arg0, arg1);
            return result;
        }
    }
    async updatePackage(arg0: PackageId, arg1: PackageInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePackage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePackage(arg0, arg1);
            return result;
        }
    }
    async updateTestimonial(arg0: TestimonialId, arg1: TestimonialInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonial(arg0, arg1);
            return result;
        }
    }
}
function from_candid_FilmCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FilmCategory): FilmCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Film_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Film): Film {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Film]): Film | null {
    return value.length === 0 ? null : from_candid_Film_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FilmId;
    title: string;
    featured: boolean;
    thumbnailUrl: string;
    createdAt: bigint;
    description: string;
    category: _FilmCategory;
    youtubeUrl: string;
}): {
    id: FilmId;
    title: string;
    featured: boolean;
    thumbnailUrl: string;
    createdAt: bigint;
    description: string;
    category: FilmCategory;
    youtubeUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        featured: value.featured,
        thumbnailUrl: value.thumbnailUrl,
        createdAt: value.createdAt,
        description: value.description,
        category: from_candid_FilmCategory_n9(_uploadFile, _downloadFile, value.category),
        youtubeUrl: value.youtubeUrl
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coupleTeaser: null;
} | {
    reel: null;
} | {
    weddingHighlights: null;
} | {
    engagement: null;
}): FilmCategory {
    return "coupleTeaser" in value ? FilmCategory.coupleTeaser : "reel" in value ? FilmCategory.reel : "weddingHighlights" in value ? FilmCategory.weddingHighlights : "engagement" in value ? FilmCategory.engagement : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Film>): Array<Film> {
    return value.map((x)=>from_candid_Film_n7(_uploadFile, _downloadFile, x));
}
function to_candid_FilmCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FilmCategory): _FilmCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_FilmInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FilmInput): _FilmInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    featured: boolean;
    thumbnailUrl: string;
    description: string;
    category: FilmCategory;
    youtubeUrl: string;
}): {
    title: string;
    featured: boolean;
    thumbnailUrl: string;
    description: string;
    category: _FilmCategory;
    youtubeUrl: string;
} {
    return {
        title: value.title,
        featured: value.featured,
        thumbnailUrl: value.thumbnailUrl,
        description: value.description,
        category: to_candid_FilmCategory_n5(_uploadFile, _downloadFile, value.category),
        youtubeUrl: value.youtubeUrl
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FilmCategory): {
    coupleTeaser: null;
} | {
    reel: null;
} | {
    weddingHighlights: null;
} | {
    engagement: null;
} {
    return value == FilmCategory.coupleTeaser ? {
        coupleTeaser: null
    } : value == FilmCategory.reel ? {
        reel: null
    } : value == FilmCategory.weddingHighlights ? {
        weddingHighlights: null
    } : value == FilmCategory.engagement ? {
        engagement: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
